### ISSUE TITLE
go build failed 

### ISSUE THREAD

**Issue by starcloud123** [qubic/go-qubic-nodes#1]
# runtime
/root/go/src/runtime/msize_allocheaders.go:16:6: roundupsize redeclared in this block
        /root/go/src/runtime/msize.go:13:6: other declaration of roundupsize
/root/go/src/runtime/map.go:357:25: too many arguments in call to roundupsize
        have (uintptr, bool)
        want (uintptr)
/root/go/src/runtime/slice.go:191:41: too many arguments in call to roundupsize
        have (uintptr, bool)
        want (uintptr)
/root/go/src/runtime/slice.go:197:56: too many arguments in call to roundupsize
        have (uintptr, bool)
        want (uintptr)
/root/go/src/runtime/slice.go:210:48: too many arguments in call to roundupsize
        have (uintptr, bool)
        want (uintptr)
/root/go/src/runtime/slice.go:218:32: too many arguments in call to roundupsize
        have (uintptr, bool)
        want (uintptr)
/root/go/src/runtime/string.go:273:36: too many arguments in call to roundupsize
        have (uintptr, bool)
        want (uintptr)
/root/go/src/runtime/string.go:288:38: too many arguments in call to roundupsize
        have (uintptr, bool)
        want (uintptr)

**Comment by LINCKODE** [comment]
Hey there!
Could you perhaps go into more detail about how you encountered this and how you're running the service?

**Comment by LINCKODE** [comment]
Hey!
I cannot replicate this on my end, could you perhaps go a bit into detail about your environment?

**Comment by starcloud123** [comment]
ubuntu version is 22.04

**Comment by LINCKODE** [comment]
Hey again!
I was unable to replicate your issue.
How did you install golang?
Maybe try reinstalling it? https://go.dev/doc/install

**Comment by LINCKODE** [comment]
After consulting with a colleague, it seems that your golang install is faulty.
Please do check this reddit thread: https://www.reddit.com/r/golang/comments/1aqi9qm/help_debugging_runtime_error_in_122/
Make sure to remove the previous installation before reinstalling!
