### ISSUE TITLE
Node suddenly stops syncing

### ISSUE THREAD

**Issue by COLUD4** [qubic/go-qubic-nodes#3]
Hello! Node suddenly stops syncing! How can I restore the node?
**version**
ghcr.io/qubic/qubic-nodes:v1.0.4

curl -s -X GET http://127.0.0.1:8001/v1/status | jq
{
  "lastProcessedTick": {
    "tickNumber": 3604324360,
    "epoch": 0
  },
  "lastProcessedTicksPerEpoch": {
    "110": 14043038,
    "111": 14212042,
    "112": 14329028,
    "113": 14409519,
    "114": 14540875,
    "115": 14687954,
    "116": 14777840,
    "117": 14870533,
    "118": 15010062,
    "119": 15130711,
    "120": 15239888,
    "121": 15380402,
    "122": 15491906,
    "123": 15578849,
    "124": 15590003,
    "125": 15700001,
    "126": 15959704,
    "127": 16089394,
    "128": 16100000
  },

**Comment by COLUD4** [comment]
> hello there! this is a known bug. a hotfix is availabe, please just update archiver to the latest version(v0.7.5).
It seems that the docker image of api 0.7.5 has not been released yet
https://github.com/qubic/qubic-http/pkgs/container/qubic-http

**Comment by LINCKODE** [comment]
i am talking about go-archiver / qubic-archiver
https://github.com/qubic/go-archiver/pkgs/container/qubic-archiver

> > hello there! this is a known bug. a hotfix is availabe, please just update archiver to the latest version(v0.7.5).
> > It seems that the docker image of api 0.7.5 has not been released yet
> > https://github.com/qubic/qubic-http/pkgs/container/qubic-http

**Comment by COLUD4** [comment]
> i am talking about go-archiver / qubic-archiver https://github.com/qubic/go-archiver/pkgs/container/qubic-archiver
> 
> > > hello there! this is a known bug. a hotfix is availabe, please just update archiver to the latest version(v0.7.5).
> > > It seems that the docker image of api 0.7.5 has not been released yet
> > > https://github.com/qubic/qubic-http/pkgs/container/qubic-http

I saw it, thank you very much for your help

**Comment by LINCKODE** [comment]
closing the issue
